digiaonline/graphql-php

- src/Language/AST/Node/ArgumentsTrait.php
- tests/Functional/Language/ParserTest.php
Well this test is probably for me to understanding how the parser parse the fragments. I thought there was a bug but probably I get it wrong.
> Parser test

- README.md
Fixes https://github.com/digiaonline/graphql-php/issues/22.
> Add Scrutinizer badge

- Resources/introspection.graphql
- src/Execution/ExecutionResult.php
- src/Type/Definition/FieldsTrait.php
- src/Type/TypeKindEnum.php
- src/Type/definition.php
- src/Type/introspection.php
- src/facades.php
- tests/Functional/Type/DefinitionTest.php
- tests/Functional/Type/IntrospectionTest.php
Gave introspection a shot, but it seems that the execution part cannot handle the query yet.
What would be the best way to solve this @hungneox?
> Initial support for introspection queries

- .idea/graphql-php.iml
- .idea/php.xml
- .travis.yml
- composer.json
- src/Execution/ExecutionArguments.php
- src/Language/AST/Schema/DefinitionBuilder.php
- src/Language/Parser.php
- src/Provider/ScalarTypesProvider.php
- src/Util/coercers.php
- tests/Functional/Execution/ExecutionTest.php
- tests/Functional/Execution/MutationTest.php
- tests/Functional/Language/ParserTest.php
It finds a lot of errors so I configured Travis CI to ignore failures from this step for now
> Start using Phpstan for static analysis

- src/Execution/ExecutionEnvironment.php
- src/Execution/Resolver/PropertyFieldResolver.php
- src/Execution/Resolver/ResolveInfo.php
- src/Execution/Resolver/ResolverInterface.php
- src/Execution/Resolver/TypeResolver.php
- src/Execution/ResponsePath.php
None of this is used currently, but I think it can give @hungneox a better idea of how the resolvers should be implemented. I'd suggest that we get this merged and take it into use later.
> Resolver concept

- src/GraphQL.php
- src/Provider/IntrospectionTypesProvider.php
- src/Type/introspection.php
Move introspection logic into a service provider.
> Add introspection provider

- .idea/php-test-framework.xml
- src/Execution/ExecutionContext.php
- src/Execution/ExecutionStrategy.php
- src/Execution/ExecutorExecutionStrategy.php
- src/Execution/Resolver/ResolveInfo.php
- src/Execution/values.php
- src/Type/Definition/ResolveTrait.php
- tests/Functional/Execution/ExecutionTest.php
- tests/Functional/Execution/MutationTest.php
@crisu83 I'm not sure if this is an expected behaviour or not but I think there should be `name` argument?
> Pass environment to resolve function

- src/Language/Printer.php
- src/Language/Writer/AbstractWriter.php
- src/Language/Writer/ArgumentWriter.php
- src/Language/Writer/BooleanValueWriter.php
- src/Language/Writer/DirectiveWriter.php
- src/Language/Writer/DocumentWriter.php
- src/Language/Writer/EnumValueWriter.php
- src/Language/Writer/FieldWriter.php
- src/Language/Writer/FloatValueWriter.php
- src/Language/Writer/FragmentDefinitionWriter.php
- src/Language/Writer/FragmentSpreadWriter.php
- src/Language/Writer/InlineFragmentWriter.php
- src/Language/Writer/IntValueWriter.php
- src/Language/Writer/ListTypeWriter.php
- src/Language/Writer/ListValueWriter.php
- src/Language/Writer/NameWriter.php
- src/Language/Writer/NamedTypeWriter.php
- src/Language/Writer/NullTypeWriter.php
- src/Language/Writer/NullValueWriter.php
- src/Language/Writer/ObjectFieldWriter.php
- src/Language/Writer/ObjectValueWriter.php
- src/Language/Writer/OperationDefinitionWriter.php
- src/Language/Writer/SelectionSetWriter.php
- src/Language/Writer/StringValueWriter.php
- src/Language/Writer/SupportedWriters.php
- src/Language/Writer/VariableDefinitionWriter.php
- src/Language/Writer/VariableWriter.php
- src/Language/Writer/WriterInterface.php
- src/Language/helpers.php
- src/Provider/PrinterProvider.php
We still need to implement the printers for SDL later.
> Add initial support for printing AST nodes

- src/Type/Schema.php
- src/Type/SchemaInterface.php
Both mutation and subscription are nullable types.
> Fix schema mutation and subscription return types

- src/Error/SyntaxErrorException.php
- src/Language/Lexer.php
- src/Language/Parser.php
- src/Language/Reader/BlockStringReader.php
- src/Language/Reader/NumberReader.php
- src/Language/Reader/StringReader.php
We could also consider adding the `GraphQLError` functionality through a trait.
> Add proper support for syntax errors

- .travis.yml
- composer.json
This makes it easier to see what's going on in one place.
Cherry-picked from https://github.com/digiaonline/graphql-php/pull/37
> Control Travis CI commands through Composer

- src/Language/helpers.php
- tests/Functional/Validation/Rule/ExecutableDefinitionsRuleTest.php
- tests/Functional/Validation/Rule/FieldOnCorrectTypeRuleTest.php
- tests/Functional/Validation/Rule/FragmentsOnCompositeTypesRuleTest.php
- tests/Functional/Validation/Rule/KnownArgumentNamesRuleTest.php
- tests/Functional/Validation/Rule/KnownDirectivesRuleTest.php
- tests/Functional/Validation/Rule/KnownFragmentNamesRuleTest.php
- tests/Functional/Validation/Rule/KnownTypeNamesRuleTest.php
- tests/Functional/Validation/Rule/LoneAnonymousOperationRuleTest.php
- tests/Functional/Validation/Rule/NoFragmentCyclesRuleTest.php
- tests/Functional/Validation/Rule/NoUndefinedVariablesRuleTest.php
- tests/Functional/Validation/Rule/NoUnusedFragmentsRuleTest.php
- tests/Functional/Validation/Rule/NoUnusedVariablesRuleTest.php
- tests/Functional/Validation/Rule/OverlappingFieldsCanBeMergedRuleTest.php
- tests/Functional/Validation/Rule/PossibleFragmentSpreadsRuleTest.php
This makes it much easier to read and write graphql in tests.
> Fix graphql indentation for validation rules

- src/Language/Visitor/SpecificKindVisitor.php
This will allow us to refactor the validation rules.
The Java implementation uses a similar approach.
> SpecificKindVisitor

- src/Execution/ExecutionStrategy.php
- src/Execution/ExecutorExecutionStrategy.php
- tests/Functional/Execution/AbstractTest.php
* Change \ArrayObject to array for easier to debug
* First Abstract test
> Execution abstract first test

- composer.json
- src/Execution/ExecutionResult.php
- src/Language/LanguageProvider.php
- src/Language/Node/EnumTypeDefinitionNode.php
- src/Language/Node/NamedTypeNode.php
- src/Language/SchemaBuilder/DefinitionBuilder.php
- src/Language/SchemaBuilder/DefinitionBuilderInterface.php
- src/Language/SchemaBuilder/ResolverInterface.php
- src/Language/SchemaBuilder/SchemaBuilder.php
- src/Language/SchemaBuilder/SchemaBuilderInterface.php
- src/Type/Definition/ResolveTrait.php
- src/Util/UtilityProvider.php
- src/api.php
- tests/Functional/QueryTest.php
- tests/Functional/starWars.graphqls
- tests/Functional/starWarsData.php
- tests/Functional/starWarsSchema.php
This pull request solves two issues:
- Basic type resolving (automatic)
- Setting resolvers on field definitions based on a resolver map
> Resolver map

- composer.json
- src/Error/UndefinedException.php
- src/Error/UndefinedFieldException.php
- src/Execution/ExecutionContext.php
- src/Execution/ExecutionStrategy.php
- src/Type/IntrospectionTypesProvider.php
- src/Type/introspection.php
- tests/Functional/Execution/AbstractTest.php
- tests/Functional/Execution/MutationTest.php
- tests/Functional/Execution/UnionInterfaceTest.php
- tests/Functional/Execution/testClasses.php
* Execution Uniion interface tests
* Fix some issue in  `introspection` definition
> Execution union interface test

- .idea/graphql-php.iml
- .idea/php.xml
- composer.json
- src/Execution/ExecutionStrategy.php
- src/Execution/ExecutorExecutionStrategy.php
- src/Type/Definition/ObjectType.php
- tests/Functional/Execution/AbstractPromiseTest.php
* Use ReactPHP Promise
* Port first two tests from `abstract-promise-test.js`
* Handles promise returns from`resolve` and `isTypeOf`
> Execution abstract promise test

- src/Execution/ExecutionStrategy.php
- src/api.php
- tests/Functional/QueryTest.php
> Fix QueryTest

- tests/Functional/ValidationTest.php
> Validation tests

- src/Cache/CacheAwareTrait.php
- src/Cache/RuntimeCache.php
- src/SchemaBuilder/DefinitionBuilder.php
This will make it easier for us to use caching across this library later.
> Add CacheAwareTrait

- src/Execution/ExecutionStrategy.php
- tests/Functional/Execution/MutationTest.php
* Implement `executeFieldsSerially`, I will refactor it later
* Porting tests from `mutation-test.js`
> Execution mutation test

- composer.json
- src/Execution/ExecutionStrategy.php
- tests/Functional/Execution/AbstractPromiseTest.php
- tests/Functional/Execution/ListTest.php
- tests/Functional/Execution/MutationTest.php
> Execution list tests

- src/SchemaBuilder/DefinitionBuilder.php
- src/SchemaBuilder/DefinitionBuilderCreator.php
- src/SchemaBuilder/DefinitionBuilderCreatorInterface.php
- src/SchemaBuilder/DefinitionBuilderInterface.php
- src/SchemaBuilder/SchemaBuilder.php
- src/SchemaBuilder/SchemaBuilderProvider.php
> Refactor DefinitionBuilder instantiation

- src/Error/SchemaValidationException.php
- src/SchemaValidator/Rule/DirectivesRule.php
- src/SchemaValidator/Rule/RootTypesRule.php
- src/SchemaValidator/Rule/TypesRule.php
- src/SchemaValidator/SchemaValidator.php
- src/SchemaValidator/SchemaValidatorInterface.php
- src/SchemaValidator/SchemaValidatorProvider.php
- src/SchemaValidator/ValidationContext.php
- src/SchemaValidator/ValidationContextCreator.php
- src/SchemaValidator/ValidationContextCreatorInterface.php
- src/SchemaValidator/ValidationContextInterface.php
- src/api.php
- Introduce separate exception for schema validation
- Rename `ValidationContextBuilder` to `ValidationContextCreator` for consistency
> Refactor schema validation

- README.md
- src/GraphQL.php
- src/SchemaBuilder/DefinitionBuilder.php
- src/SchemaBuilder/DefinitionBuilderCreator.php
- src/SchemaBuilder/DefinitionBuilderCreatorInterface.php
- src/SchemaBuilder/DefinitionBuilderInterface.php
- src/SchemaBuilder/ResolverMapRegistry.php
- src/SchemaBuilder/ResolverRegistryInterface.php
- src/SchemaBuilder/SchemaBuilder.php
- src/SchemaBuilder/SchemaBuilderInterface.php
- src/SchemaBuilder/SchemaBuilderProvider.php
- tests/Functional/Language/SchemaParserTest.php
- tests/Functional/SchemaValidator/ValidationTest.php
> Resolver registry

- src/Execution/ValuesHelper.php
- src/Execution/values.php
- src/Util/TypeHelper.php
- src/Util/ValueHelper.php
- src/Validation/comparators.php
Move comparator functions into associated helpers.
> Refactor comparators to use the container

- tests/Unit/Language/BlockStringValueTest.php
> Add block string value unit tests

- src/Execution/ExecutionStrategy.php
> Fix type-hint for buildLocatedError

- src/Error/CoercingException.php
- src/Error/InvalidTypeException.php
- src/Execution/CoercedValue.php
- src/Execution/Execution.php
- src/Execution/ExecutionContextBuilder.php
- src/Execution/Path.php
- src/Execution/ValuesHelper.php
- src/Execution/values.php
- src/Language/Node/EnumValueNode.php
- src/Language/Node/ListValueNode.php
- src/Language/Node/NonNullTypeNode.php
- src/Language/Node/VariableDefinitionNode.php
- src/Type/IntrospectionProvider.php
- src/Util/ValueHelper.php
- tests/Functional/Execution/VariablesTest.php
- tests/Unit/Util/ValueHelperTest.php
Porting tests from `variables-test.js`
+ Add `coerceVariableValues` function
+ Support for printing path
+ Support for default variable input value
> Execution variable test

- src/Error/GraphQLException.php
- src/Language/ASTBuilder.php
- src/Language/Lexer.php
- src/Language/SourceLocation.php
- src/Language/Token.php
- src/Language/TokenReader.php
- src/Language/TokenReaderInterface.php
- src/Language/utils.php
- tests/Functional/Language/ParserTest.php
- tests/Unit/Language/LexerTest.php
> Lexer unit tests

- src/Execution/ExecutionContext.php
- src/Execution/ExecutionContextBuilder.php
- src/Execution/Executor.php
- src/Execution/FieldCollector.php
* Introduce new FieldCollector class, basically move field collecting stuff out from executor
> Introduce FieldCollector

- src/Type/Definition/Field.php
- src/Type/Definition/FieldsTrait.php
- src/Type/Definition/ObjectType.php
- src/Type/IntrospectionProvider.php
I noticed that we didn't have a subscribe method for fields so I added it based on the reference impl.
> Introduce subscribe method to Field

- src/Execution/Execution.php
- src/Execution/ExecutionInterface.php
- src/Execution/Executor.php
- src/Execution/FieldCollector.php
- src/Type/Definition/TypeInterface.php
- Add missing type-hints and PhpDoc
> Missing type hints

- src/Schema/Schema.php
- src/Type/Definition/EnumType.php
- src/Type/Definition/InputField.php
- src/Type/Definition/InterfaceType.php
- src/Type/definition.php
Refactor type definition functions to use destructor syntax (thanks @hungneox).
> Refactor type definition functions

- README.md
Add related packages to README.
> Related packages

- tests/Functional/Execution/ResolveTest.php
- tests/Functional/Execution/SchemaTest.php
- tests/Functional/Execution/VariablesTest.php
> #219 Add unit test for custom scalar Date type

- src/Schema/Building/BuildInfo.php
Fix bug related to resolving operation types when building a schema.
> Fix resolving of operation types during build

- src/Error/ResolutionException.php
- src/Execution/ExecutionInterface.php
- src/Execution/ResolveInfo.php
- src/Execution/ValuesHelper.php
- src/GraphQL.php
- src/Language/Node/DefaultValueTrait.php
- src/Language/Node/TypeTrait.php
- src/Language/Node/ValueLiteralTrait.php
- src/Language/NodeBuilder.php
- src/Language/Token.php
- src/Schema/Resolver/ResolverRegistry.php
- src/Schema/utils.php
- src/Type/Definition/ObjectType.php
- src/Type/definition.php
- src/Util/ValueHelper.php
- src/Util/helpers.php
- src/api.php
> Fix a bunch of smaller Scrutinizer issues

- README.md
- src/Execution/ValuesHelper.php
- src/Type/ScalarTypesProvider.php
- src/Util/utils.php
- tests/Functional/Execution/MutationTest.php
Changes proposed in this pull request:
* No need to capitalise 'Abstract Syntax Tree'
* Fix typos
* HTTP -> HTTPS and update a redirect
> Minor documentation changes

- src/Language/Parser.php
Remove notes on SDL being experimental (#235).
Fixes #243.
> Non-experimental SDL

- README.md
> Link to read-only README of graphql-relay-php

- src/Language/Parser.php
- src/Language/ParserInterface.php
- tests/Functional/Language/ParserTest.php
Add initial support for partial parsing (fixes #234).
> Parse partial

- .idea/graphql-php.iml
- .idea/php.xml
- README.md
- composer.json
>  Replace symfony/polyfill-mbstring with a hard ext-mbstring requirement

- README.md
> Make the README instructions work by specifying dev-master

- composer.json
- src/Error/GraphQLException.php
- src/Schema/Building/BuildInfo.php
- src/Schema/Extension/ExtensionContext.php
- src/Schema/Schema.php
- src/Schema/Validation/SchemaValidator.php
- src/Schema/Validation/ValidationContext.php
- src/Schema/Validation/ValidationContextInterface.php
- src/Type/Definition/CompositeTypeInterface.php
- src/Type/Definition/InputTypeInterface.php
- src/Type/Definition/LeafTypeInterface.php
- src/Type/Definition/OutputTypeInterface.php
- src/Type/Definition/SerializableTypeInterface.php
- src/Util/TypeInfo.php
- src/Validation/Rule/UniqueArgumentNamesRule.php
- src/Validation/Rule/UniqueFragmentNamesRule.php
- src/Validation/Rule/UniqueInputFieldNamesRule.php
- src/Validation/Rule/UniqueOperationNamesRule.php
- src/Validation/Rule/UniqueVariableNamesRule.php
21 errors remaining for level 4, will tackle those after this is merged
> Bump phpstan analysis level to 3

- composer.json
- src/Execution/Execution.php
- src/Execution/Executor.php
- src/Execution/ValuesHelper.php
- src/Language/Lexer.php
- src/Language/NodePrinter.php
- src/Schema/Validation/Rule/DirectivesRule.php
- src/Schema/Validation/Rule/TypesRule.php
- src/Type/Coercer/IntCoercer.php
- src/Type/Definition/ObjectType.php
- src/Type/Definition/ScalarType.php
- src/Type/Definition/SerializableTypeInterface.php
- src/Type/IntrospectionProvider.php
- src/Util/ValueConverter.php
- src/Validation/ValidationContext.php
- src/Validation/Validator.php
- tests/Functional/Type/SerializationTest.php
- tests/Unit/Type/Coercer/IntCoercerTest.php
- tests/Unit/Util/ValueConverterTest.php
@crisu83 this actually fixes some bugs so in my opinion it's important that we get it in.
>  Bump the phpstan analysis level to 4 

- src/Language/Lexer.php
- tests/Functional/Language/ParserTest.php
- tests/Unit/Language/LexerTest.php
> Fix two lexer issues

- .gitignore
- README.md
The initial draft of the readme for this project.
I removed the Motivation and Architecture -sections for now. 
We can decide later if we'll add them back or not.
> Readme draft

- README.md
> README (alpha)

- tests/Unit/Language/NodeBuilderTest.php
Add unit tests for `NodeBuilder` (fixes #245).
> NodeBuilder tests

- src/Language/Node/EnumTypeDefinitionNode.php
- src/Language/Node/InputObjectTypeDefinitionNode.php
- src/Language/Node/InterfaceTypeDefinitionNode.php
- src/Language/Node/NamedTypeNode.php
- src/Language/Node/NamedTypeNodeInterface.php
- src/Language/Node/ObjectTypeDefinitionNode.php
- src/Language/Node/ScalarTypeDefinitionNode.php
- src/Language/Node/TypeNodeInterface.php
- src/Language/Node/TypeSystemDefinitionNodeInterface.php
- src/Language/Node/UnionTypeDefinitionNode.php
- src/Schema/Building/BuildingContext.php
- src/Schema/DefinitionBuilder.php
- src/Schema/DefinitionBuilderInterface.php
Add interface for named type nodes.
> Named type node interface

- README.md
Fixed the custom scalar example in the readme.
> Fix custom scalar example

- src/Execution/ValuesHelper.php
- tests/Functional/Execution/ValueHelperTest.php
- tests/Functional/Execution/ValuesHelperTest.php
> Fix coercing false non-null booleans

- composer.json
- src/Schema/Building/SchemaBuilder.php
- src/Schema/Building/SchemaBuildingProvider.php
- src/Schema/DefinitionBuilder.php
- src/Schema/Extension/ExtensionContext.php
- src/Schema/Extension/SchemaExtensionProvider.php
I removed the simple cache dependency, because we don't use it anymore.
> Remove simple cache dependency

- composer.json
- src/Execution/ExecutionProvider.php
- src/GraphQL.php
- src/Language/LanguageProvider.php
- src/Schema/Validation/SchemaValidationProvider.php
- src/Type/CoercerProvider.php
- src/Type/DirectivesProvider.php
- src/Type/IntrospectionProvider.php
- src/Type/ScalarTypesProvider.php
- src/Type/scalars.php
- src/Validation/ValidationProvider.php
Upgrade league/container to current version.
> Upgrade league/container

- src/Schema/Resolver/AbstractResolver.php
- src/Schema/Resolver/ResolverCollection.php
- src/Schema/Resolver/ResolverInterface.php
- src/Schema/Resolver/ResolverRegistry.php
- tests/Unit/Schema/Resolver/ResolverRegistryTest.php
Add support for applying specific middleware to resolvers.
> Named resolver middleware

- src/Schema/DefinitionPrinter.php
- src/Type/Definition/FieldsTrait.php
- src/Validation/Rule/VariablesInAllowedPositionRule.php
> Fix some invalid docblocks

- src/Execution/Executor.php
- tests/Functional/Execution/ExecutionTest.php
- Previously it seems like we still can return null for non-nullable field
> Fix a bug which causes non-nullable field can return null

- src/Execution/ValuesHelper.php
Fix a bug that caused coercing of enum values to fail.
> Fix coercing values for enum type

- src/Execution/ValuesHelper.php
- tests/Functional/Execution/ValuesHelperTest.php
> Fix "Cannot use false as value for non-null booleans in input types"

- README.md
> Fix resolver example

- src/Execution/ExecutionResult.php
- tests/Unit/Execution/ExecutionResultTest.php
> Fix wrong type-hints in ExecutionResult

- src/Execution/Execution.php
Move error handling after resolving promise.
> Move error handling

- src/Language/DirectiveLocationEnum.php
- src/Language/utils.php
- src/Schema/DefinitionPrinter.php
- src/Schema/utils.php
- src/Type/Definition/ArgumentsTrait.php
- src/Type/DirectivesProvider.php
- src/Type/IntrospectionProvider.php
- tests/Functional/Schema/DefinitionPrinterTest.php
Fix the ignored test cases in `DefinitionPrinterTest`.
> Fix definition printer tests

- README.md
Fix before- and after middleware examples in the README.
> Fix middleware examples (fixes #341)

- .idea/inspectionProfiles/Project_Default.xml
- src/Error/GraphQLException.php
- src/Execution/Execution.php
- src/Execution/Strategy/AbstractExecutionStrategy.php
- src/Execution/Strategy/FieldCollector.php
- src/Execution/ValuesResolver.php
- src/Language/Visitor/TypeInfoVisitor.php
- src/Schema/DefinitionBuilder.php
- src/Type/Definition/DefaultValue.php
- src/Util/TypeInfo.php
- src/Util/ValueASTConverter.php
- src/Validation/Rule/ProvidedRequiredArgumentsRule.php
- src/Validation/Rule/SupportedRules.php
- src/Validation/Rule/ValuesOfCorrectTypeRule.php
- src/Validation/RulesProvider.php
- src/Validation/ValidationContext.php
- tests/Functional/Execution/ExecutionTest.php
- tests/Functional/Execution/NonNullTest.php
- tests/Functional/Execution/VariablesTest.php
- tests/Functional/Schema/DefinitionPrinterTest.php
- tests/Functional/Validation/Rule/OverlappingFieldsCanBeMergedRuleTest.php
- tests/Functional/Validation/Rule/ProvidedRequiredArgumentsRuleTest.php
- tests/Functional/Validation/Rule/RuleTestCase.php
- tests/Functional/Validation/Rule/ValuesOfCorrectTypeRuleTest.php
- tests/Functional/Validation/harness.php
- tests/TestCase.php
- tests/Unit/Execution/ExecutionResultTest.php
- tests/Unit/Util/ValueASTConverterTest.php
Fixes ambiguity with null variable values and default values (fixes #239).
> Fix null variables and default values
