digiaonline/graphql-php

- src/Execution/ExecutionResult.php
- src/Execution/ExecutionStrategy.php
- src/Execution/ExecutorExecutionStrategy.php
- tests/Functional/Execution/ExecutionTest.php
I have to improve the implementation a lot more but basically now the execution can execute multiple fragments.
It's done in a recursive way which I think not so good. I will try to do it in non-recursive way.
> Execution fragments deeper

- src/GraphQL.php
- src/Language/AST/Builder/SupportedBuilders.php
- src/Language/Reader/SupportedReaders.php
- src/Provider/CacheProvider.php
- src/Provider/DirectivesProvider.php
- src/Provider/ParserProvider.php
- src/Provider/PrinterProvider.php
- src/Provider/ScalarTypesProvider.php
- src/Provider/SchemaBuilderProvider.php
I moved container bindings into service providers to make use of its lazy registration. This means that classes are not instantiated before they are actually needed. This should also improve code quality.
> Refactor container builder to use providers

- src/Execution/ExecutionStrategy.php
- src/Execution/values.php
- src/helpers.php
- tests/Functional/Execution/ExecutionTest.php
- tests/Functional/Execution/MutationTest.php
- tests/Functional/Execution/ValuesTest.php
- Change all tests to use `graphql()` helper
- Remove `execute()` helper
> Simplify unit test using graph helper

- src/SchemaBuilder/DefinitionBuilder.php
- src/SchemaValidator/Rule/TypesRule.php
- src/Type/Definition/TypeTrait.php
- src/Type/Schema.php
- src/Util/helpers.php
- tests/Functional/SchemaValidator/ValidationTest.php
Added all the remaining `SchemaValidator` test cases, except those that require support for extending schema. Created a separate issue for implementing schema extension (#147) and will add the missing test cases once that issue has been resolved.
> SchemaValidator tests

- src/GraphQL.php
- src/SchemaValidator/Rule/SupportedRules.php
- src/Type/directives.php
- src/Type/introspection.php
- src/Type/scalars.php
- src/Validation/Rule/SupportedRules.php
- src/api.php
- tests/Functional/Execution/ExecutionTest.php
- tests/Functional/Execution/ValuesResolverTest.php
- tests/Functional/IntrospectionTest.php
- tests/Functional/SchemaValidator/ValidationTest.php
- tests/Functional/Validation/Rule/RuleTestCase.php
- tests/Functional/Validation/ValidationTest.php
Refactor the public API to make it easier for developers to use the library, even without using the namespaced functions found in [api.php](../tree/master/src/api.php). I also changed the `graphql` function to return an array instead of `ExecutionResult`. This makes testing a bit more simple because we do not have to instantiate new `ExecutionResult` objects to be able to assert results.
> Refactor public API

- src/Schema/DefinitionBuilder.php
- src/Schema/Extension/ExtendInfo.php
- src/Schema/Extension/ExtensionContext.php
- src/Schema/Validation/Rule/TypesRule.php
- tests/Functional/Schema/ValidationTest.php
Add missing schema validation tests that were initially skipped because we did not support schema extension back when they were written.
> Missing schema validation tests

- src/Schema/Building/SchemaBuilder.php
- src/Schema/Building/SchemaBuilderInterface.php
- src/Schema/Building/SchemaBuildingProvider.php
- src/Schema/DefinitionBuilder.php
- src/Schema/DefinitionBuilderInterface.php
- src/Schema/Extension/SchemaExtender.php
- src/Schema/Extension/SchemaExtenderInterface.php
- src/Schema/Extension/SchemaExtensionProvider.php
Initial logic for supporting passing of custom types and directives at build time when using SDL to define your schema.
Here's an example of how you'd use a custom type with your SDL schema:
```php
$schemaDef = file_get_contents(__DIR__ . '/schema.graphqls');
$dateType = newScalarType([
'name'         => 'Date',
'serialize'    => function (DateTime $value) {
return $value->format('Y-m-d');
},
'parseValue'   => function ($value) {
return new DateTime($value);
},
'parseLiteral' => function ($node) {
return $node->getValue();
},
]);
$executableSchema = buildSchema($schemaDef, [
'Query' => QueryResolver::class,
], [
'types' => [$dateType],
]);
```
> Support for custom types and directives when building schema

- src/Language/Node/AbstractNode.php
- src/Language/Node/ArgumentNode.php
- src/Language/Node/DirectiveNode.php
- src/Language/Node/DocumentNode.php
- src/Language/Node/NameNode.php
- src/Language/Node/ObjectFieldNode.php
- src/Language/Node/SelectionSetNode.php
- src/Language/Visitor/AcceptsVisitorsInterface.php
- src/Language/Visitor/AcceptsVisitorsTrait.php
Refactor the AST to make more sense, which allowed for typing fields in the `Schema` class more implicitly.
> Refactor AST

- src/Execution/ExecutionResult.php
Update ExecutionResult field order according to the June 2018 spec (#235).
> ExecutionResult field order

- tests/Functional/Execution/DirectivesTest.php
- tests/Functional/Execution/ExecutionTest.php
- tests/Functional/Execution/UnionInterfaceTest.php
- tests/Functional/Execution/ValueHelperTest.php
- tests/Functional/Type/DefinitionTest.php
- tests/Unit/Language/BlockStringValueTest.php
- tests/Unit/Type/Coercer/IntCoercerTest.php
- tests/Unit/Util/AbstractEnumTest.php
- tests/Unit/Util/ValueASTConverterTest.php
Luckily, nothing did break because of this, so the code seems fine as is!
Still, going forward we should aim to use assertSame wherever possible,
as it uses triple equal sign comparison.
> Change a bunch of assertions from assertEquals to assertSame

- src/GraphQL.php
The container's make() method obviously doesn't know what it returns so we have to add @var annotations here and there
> Add some intermediate variables so type-hint information isn't lost

- README.md
Update README.md to not tell developers to use `dev-master` when installing the package.
> Do not use dev-master

- README.md
- src/Error/FileNotFoundException.php
- src/Language/FileSourceBuilder.php
- src/Language/MultiFileSourceBuilder.php
- src/Language/SourceBuilderInterface.php
- tests/Functional/Language/FileSourceBuilderTest.php
- tests/Functional/Language/MultiFileSourceBuilderTest.php
The FileSourceBuilder just does \file_get_contents() on a file, so it's not that useful unless we change the API to accept only Source and not string.
The DirectorySourceBuilder is more interesting since it allows people to split their giant SDL files into multiple logic units (e.g. one for Relay, one for common sorting/ordering stuff, etc.).
> Add a SourceBuilderInterface along with two basic implementations

- src/Execution/Executor.php
Fixed an issue that caused errors and exceptions to be swallowed by the `Executor`.
> Fix error bubbling for executeFieldsSerially

- tests/Functional/Validation/Rule/FieldOnCorrectTypeRuleTest.php
- tests/Functional/Validation/harness.php
The CatOrDog union type definition in harness.php was wrong, in the reference implementation it is indeed "Dog, Cat", not "Cat, Dog", even though the union name is "CatOrDog"
> Fix the incomplete FieldOnCorrectTypeRuleTest testcase

- src/GraphQL.php
- src/Language/Parser.php
- src/Language/ParserInterface.php
- src/Language/StringSourceBuilder.php
- src/api.php
- tests/Functional/Language/ParserTest.php
- tests/Functional/Language/StringSourceBuilderTest.php
- tests/Unit/Language/LexerTest.php
String source builder, stop passing around both strings and Source objects.
This way we can use static type-hinting, which in this case unearthed a bug with how lex methods are called in the parser.
> String source builder

- README.md
The Relay support section is no longer needed because of the Related projects section.
> Remove relay support section

- src/Schema/Resolver/AbstractFieldResolver.php
- src/Schema/Resolver/AbstractTypeResolver.php
- src/Schema/Resolver/ResolverCollectionInterface.php
- src/Schema/Resolver/ResolverMap.php
- src/Schema/Resolver/ResolverRegistry.php
- src/Schema/Resolver/ResolverTrait.php
- tests/Unit/Schema/Resolver/ResolverRegistryTest.php
Re-introduce type resolvers because this will allow developers to apply middleware on the type-level in addition to field-level and global-level.
> Type resolver

- src/Execution/CoercedValue.php
- src/Execution/ValuesHelper.php
- tests/Functional/Execution/ValuesHelperTest.php
Fixed a bug that caused `false` values to be coerced as `null`.
> Fix coercing of false values

- src/Language/Node/AbstractNode.php
- src/Language/Node/NodeInterface.php
- src/Language/Visitor/VisitorInfo.php
- src/Util/NodeComparator.php
- src/Validation/ValidationContext.php
- src/Validation/Validator.php
- tests/Functional/Language/VisitorTest.php
- tests/Unit/Util/NodeComparatorTest.php
Introduce visitor info concept to separate the visiting logic from the node logic. Visitor info is immutable so it should reduce the number of potential bugs in the visiting process as well.
This is also something I wanted to do before we start working on the immutable AST and schema directives.
> Visitor info

- src/Execution/Execution.php
- src/Execution/ExecutionInterface.php
- src/GraphQL.php
- src/api.php
- New `promiseExecute` method in `Execution.php`
- Helpers for API (`graphqlAsync()`, `processAsync`)
> Adds support for asynchronous executions via Promises

- src/Language/utils.php
> PHP Deprecated: Array and string offset access syntax with curly braces is deprecated.
This PR fixes this.
> Fix PHP deprecations
